- name: BPI-CM4 Setup armbian prerequisite & env
  hosts: all
  become: true
  vars:
    disable_wifi: true    # true (default) Wifi support is disabled
    disable_ramlog: false   # false (default) RamLog and /tmp use RAM not internal storage (EMMC)
    everyday_user: pi     # user for everyday use
    ansible_remote_tmp: ~/.ansible/tmp/
  handlers:
    - name: Reboot machine
      ansible.builtin.reboot:
  tasks:
    - name: Give all sudo permission for {{ everyday_user }}
      community.general.sudoers:
        name: "{{ everyday_user }}_permission"
        user: "{{ everyday_user }}"
        commands: ALL
        nopassword: true

    # disabling /tmp tmpfs and related services
    # https://ubuntu-mate.community/t/chattr-inappropriate-ioctl-for-device-while-reading-flags-on-need-help/20872
    - name: Disable RamLog & ZRAM
      when: disable_ramlog | bool
      block:
        - name: Disable RamLog & ZRAM
          ansible.builtin.lineinfile:
            path: '{{ item }}'
            regexp: '^ENABLED=true$'
            line: ENABLED=false
          loop:
            - /etc/default/armbian-zram-config
            - /etc/default/armbian-ramlog

        - name: Disable /tmp tmpfs in fstab
          ansible.posix.mount:
            path: /tmp
            src: tmpfs
            fstype: tmpfs
            opts: defaults,nosuid
            state: absent_from_fstab
          notify: Reboot machine

    - name: Force handlers to run (reboot)
      ansible.builtin.meta: flush_handlers

    # disable Wifi on bananapi armbian (it's getting too hot and i'm not using wifi or BT)
    - name: Disable Wifi module and service
      when: disable_wifi | bool
      block:
        - name: Stop & disable wpa_supplicant service
          ansible.builtin.systemd:
            name: wpa_supplicant
            state: stopped
            enabled: false

        - name: Unload wifi module 88x2cs
          community.general.modprobe:
            name: 88x2cs
            state: absent

        - name: Blacklist WiFi module
          ansible.builtin.copy:
            dest: "/etc/modprobe.d/blacklist.conf"
            owner: root
            group: root
            mode: '0644'
            content: >
              blacklist 88x2cs
          notify: Reboot machine

        # This can't be done this way so the above workarroud was used
        # because when /tmp is tmpfs ansible can't change permission on filz
        # 

        # - name: Blacklist WiFi module
        #   community.general.kernel_blacklist:
        #     name: 88x2cs
        #     state: present

    - name: "Set hostname to {{ inventory_hostname }}"
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update hostname in /etc/hosts
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: 'bananapicm4io'
        replace: "{{ inventory_hostname }}"
